### ISSUE TITLE
Slack link for on filecoin landing page is no longer active  

### ISSUE THREAD

**Issue by annakaz** [filecoin-project/community#117]
Slack link: https://filecoinproject.slack.com/join/shared_invite/zt-nik8tcn4-v~7aPCfoIJHqoNY7wrK8OQ#/
shows "This link is no longer active" error
I<img width="1110" alt="Screen Shot 2021-03-24 at 9 56 52 PM" src="https://user-images.githubusercontent.com/16907027/112421189-d98c8400-8ceb-11eb-805e-5a18b9e98eba.png">

**Comment by angiemaguire** [comment]
@annakaz Thanks for opening this issue. We're reviewing now.

**Comment by andyschwab** [comment]
This is fixed!

**Comment by tabcat** [comment]
This is the case again for the repo and filecoin.io footer slack link
