### ISSUE TITLE
Sunset discussion.filecoin.io

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/community#150]
Sunset discussion.filecoin.io project:
- [x] @jennijuju Update readme with clearer community platform navigation and up-to-date resources #149 
- [x] @andyschwab Inform discourse filecoin uses that it will be deprecated this friday and add link redirection to this repo
- [x] @andyschwab update the filecoin.io
- [x] @johnnymatthews update forum lilnks in docs.filecoin.io

**Comment by johnnymatthews** [comment]
[This merge does my bit :)](https://github.com/filecoin-project/filecoin-docs/pull/828)

**Comment by andyschwab** [comment]
[filecoin.io link updates](https://github.com/filecoin-project/website-new/pull/331), ready to go with your review @jennijuju

**Comment by jennijuju** [comment]
> [filecoin.io link updates](https://github.com/filecoin-project/website-new/pull/331), ready to go with your review @jennijuju

Reviewed!

**Comment by jennijuju** [comment]
Woohoo! Ready to 🌆
