### ISSUE TITLE
Mining call 1 recording?

### ISSUE THREAD

**Issue by bcomnes** [filecoin-project/community#16]
Did the mining call recording get posted anywhere? I unfortunately missed it and was hoping to catch it on the recording. 
<img width="791" alt="Screen Shot 2019-05-15 at 11 57 02 AM" src="https://user-images.githubusercontent.com/166301/57766997-ae58a700-7708-11e9-8730-482278a48432.png">

**Comment by liao1k** [comment]
I am waiting for the conference call video also. Please let us know when you post that video file on the community repo. Thanks.

**Comment by BravoJason** [comment]
> I am waiting for the conference call video also. Please let us know when you post that video file on the community repo. Thanks.

Me too. I'm waiting for the video as well.

**Comment by cahlenlee** [comment]
Same here

**Comment by jimpick** [comment]
It's up now!

https://www.youtube.com/watch?v=bpKKgkPmA_w

**Comment by bcomnes** [comment]
@jimpick ftw!
