### ISSUE TITLE
Mining and Dev Community calls links are 404

### ISSUE THREAD

**Issue by axelsimon** [filecoin-project/community#18]
In the README.md, both links are dead:

>Learn more about:
>
>    [Development Community Calls](https://github.com/filecoin-project/community/blob/master/community-calls/dev-calls.md)
 >    [Mining Community Calls](https://github.com/filecoin-project/community/blob/master/)

I have a feeling @pooja might know how to help out on this! :)

**Comment by jimpick** [comment]
I see an unapproved pull request here:

https://github.com/filecoin-project/community/pull/15

**Comment by pooja** [comment]
Thank you @axelsimon and @jimpick! Indeed that PR should fix it. Thanks @jamiew for the fix. Let me know if that doesn't fix it for some reason!

**Comment by kdunn926** [comment]
Having a "not quite 404" - more like an ipfs http gateway latency issue - loading stall out here:

![image](https://user-images.githubusercontent.com/7925800/59956989-6e948600-9451-11e9-8aa1-0ea529e7c3f3.png)

**Comment by pooja** [comment]
I believe this issue has been resolved. Please reopen if not!
