### ISSUE TITLE
Mind announce the Community Meetup list?

### ISSUE THREAD

**Issue by Cyanglacier** [filecoin-project/community#24]
So glad that Protocol labs could come to ShenZhen. But I’m not sure i can join this and if it is true... The price of traveling to ShenZhen is little expensive for me:((Booking tickets is necessary)
Hope guys could have an announcement quickly:)

**Comment by michellebrous** [comment]
Hi, thanks for writing to us. We're sorry for the late reply, we've been busy preparing for the meetup here. We hope to see you at the next one!
