### ISSUE TITLE
非常期待这次会议

### ISSUE THREAD

**Issue by yangjian102621** [filecoin-project/community#25]
Name:RockYang（阳建）
Email: yangjian101621@gmail.com
Affiliations: 深圳星际鑫航科技有限公司
Github handle: yangjian102621

I will attend the meetting on time. wish the meeting a complete success.

**Comment by taoshengshi** [comment]
Name: tshi
Email: learning_ss@126.com
Affiliations: ProtoShool Organizer
Github handle: taoshengshi

I will attend the meeting on time. wish the meeting a complete success.

**Comment by michellebrous** [comment]
Thanks, you'll receive an email invite shortly!
