### ISSUE TITLE
Template Issues for Storage Provider Bug Bounties

### ISSUE THREAD

**Issue by dud1337** [filecoin-project/community#263]
We'd like some templates for the storage provider bug bounties.

If the Markdown is submitted for these tempaltes *here*, I can forge the PRs.

cc @vnessasgrt @jennijuju

**Comment by vnessasgrt** [comment]
Template Name: Bounty Issue
About: Submit issues to help improve our community
Issue default title : [Bounty Issue]  <Your Title Here>
Template content:
## 1. Proposed issue:

## 2. Why is this issue important?

## 3. Tasks

## 4. Additional Context



Template Name: Bounty Claim
About: Claim a bounty for a completed work
Issue default title : [Bounty Issue]  <Your Title Here>
Template content:
## What Bounty is this claiming?

## What Pull Request contains the solution?
<!-- link to Pull Request closing the Bounty issue, the Pull Request must be merged and you must be the primary author →
## Contact Information
<!-- IMPORTANT: once you're done, please send a link to this issue AND your payment information to storageproviderbounties@fil.org→

**Comment by dud1337** [comment]
This looks great, thank you, @vnessasgrt 

I'll work on a PR now.

**Comment by dud1337** [comment]
Thanks, @Stefaan-V
