### ISSUE TITLE
About Developer Testing Version

### ISSUE THREAD

**Issue by wanghongji1** [filecoin-project/community#32]
Is the open beta version of Filecoin an invitation system?

**Comment by eshon** [comment]
@wanghongji1 - There's no invitation system. Anyone can join one of the Devnets and everything is open source. You can find instructions at [docs.filecoin.io](https://docs.filecoin.io).

**Comment by wanghongji1** [comment]
> @ wanghongji1-没有邀请系统。任何人都可以加入其中一个Devnet，一切都是开源的。您可以在[docs.filecoin.io中](https://docs.filecoin.io)找到说明。

 
并不是Devnet，而是12月11日的公开测试版本是否有邀请
It's not Devnet, it's whether there's an invitation for the public beta version on December 11

**Comment by eshon** [comment]
@wanghongji1 - The Filecoin project is open source on Github, anyone can choose to run Filecoin nodes and Testnet will be open to the public for anyone to mine. There will be **no** invitation system to a beta version. At launch, how to join the network will be published in the Docs and/or Github.
