### ISSUE TITLE
[Storage Provider Bounty Claim] Estuary Shuttle/Node

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/community#373]
## 1. What Bounty is this issue claiming?

Providing Estuary with an uncapped node in the Dcent Hosting B.V. datacenter.
The node consist of 10Gbe uncapped networking, 1TB RAM, 15TB NVME and an Epic 7282 CPU.

Pricing as is for the uncapped node is 2.500 USD/monthly. Started from October 2021. 

## 2. What Pull Request contains the solution?

No solution provided. 

## Contact Information

Email: info@dcent.nl 
Wallet: f12fi2tcsxxliu7gwj6zoxj62dsfjsvdlqhkcpqwi

**Comment by jennijuju** [comment]
@vnessasgrt we'd recommend a $2000/mo for a two months service bounty.

**Comment by cryptowhizzard** [comment]
That is okay with us @jennijuju @vnessasgrt.

**Comment by jennijuju** [comment]
Based on this [message](https://filecoinproject.slack.com/archives/C016APFREQK/p1636460659448100)
> We are running one shuttle now who is maintained and installed by @Why and @lanzafame
seems like the service was provided for one month (Oct) instead of two.

therefore, I'd suggest to approve a $2000 reward for this claim. cc @vnessasgrt please review and let us know if you have any questions.

**Comment by cryptowhizzard** [comment]
@jennijuju The server is running since 08-09-2021 and is still running today 09-11-2021 so that is over two months now. @whyrusleeping can confirm.

**Comment by cryptowhizzard** [comment]
@jennijuju Counting from 01-10-2021 is fine. We'll keep the first month for our own cost.

**Comment by jennijuju** [comment]
as Why needs more time to move the data off safely, we'd like to extend the bounty to three months (Oct, Nov, Dec) on the condition that the shuttle is maintained till the end of the year.

**Comment by cryptowhizzard** [comment]
Hello @jennijuju 

We are happy to extend for another month.

Months of October and november are still open. When can we expect payment?

**Comment by vnessasgrt** [comment]
We will send you the payment information that are needed to be filled via email.

**Comment by cryptowhizzard** [comment]
@vnessasgrt we have not received anything by mail yet. Have we missed something?

**Comment by vnessasgrt** [comment]
This bounty is completed

**Comment by whyrusleeping** [comment]
Thanks everyone!
