### ISSUE TITLE
Watch discuss.filecoin.io or drive people away from it.

### ISSUE THREAD

**Issue by bertrandfalguiere** [filecoin-project/community#38]
The [official discussion forum](https://discuss.filecoin.io) about Filecoin, which is featured in the Readme of this very repo, is ghosted by the Filecoin team. 

[There re several different occurrences of people complaining having no answer after a long time](https://discuss.filecoin.io/t/getting-started-questions/294/6), and a lot of unanswered posts even though there are not many posts (maybe for that very reason). 

I think the Filecoin team should at least publish a post explaining that most of the fun happens on Matrix, Slack, etc.
The link to the forum should be removed from the Readme, or the team should watch it carefully. 

The forum as it is makes it look to new comers like Filecoin is a dead project (which it is everything but, of course). 

Just a thought.

**Comment by mishmosh** [comment]
@bertrandfalguiere We've finally migrated the Filecoin discussion forum to https://github.com/filecoin-project/community/discussions, and redirected the old URL. Your nudge was much appreciated - thank you.
