### ISSUE TITLE
create and bridge IRC channels to matrix/slack

### ISSUE THREAD

**Issue by pooja** [filecoin-project/community#4]
IRC channels will help us get in touch with a significant portion of our community that really prefers to use IRC over Matrix and Slack. We currently have several chat channels created in [Matrix](https://matrix.org). We chose Matrix because it uses a decentralized, p2p protocol, and channels can be encrypted end-to-end. Matrix also makes it easy to integrate with other chat services.

Currently, we have bridged our Matrix channels to Slack. We want our core channels (listed below) to be bridged to IRC as well.

This issue requires two main steps:

1) Create IRC channels for:
- fil-dev
- fil-proofs
- fil-chat
- fil-mining
- fil-devex-docs

2) Then, bridge these IRC channels to our Matrix channels (which the Slack channels are also bridged to).

**Comment by pooja** [comment]
This needs to be updated to whatever our current main community channels are (there should more than the ones listed here!)

**Comment by wolfduan** [comment]
when can we ming on filecoin network?

**Comment by JayDoubleu** [comment]
So, is there any news on this ?

**Comment by pooja** [comment]
We have not implemented this, but anyone in the community should feel free to pick this up! We're happy to support however we can. Just let us know!

**Comment by mishmosh** [comment]
Closing this issue. If there is community interest, please comment on this issue and we will re-open.

**Comment by eighthave** [comment]
There has been some progress here, I'm in one bridged room at least.  It seems to be Slack-Matrix-Discord.  I don't know if it is publicly documented yet.

**Comment by eighthave** [comment]
I found the matrix server: In Element:
1. Go to Explore Rooms
2. Click the Show menu
3. Click "Add new server..." at the bottom
4. Enter `ipfs.io`
