### ISSUE TITLE
[Storage Provider Bounty Issue] Video Tutorial on Hardware Specs for Storage Providers

### ISSUE THREAD

**Issue by vnessasgrt** [filecoin-project/community#454]
## 1. Proposed issue:
Video guidance on hardware specs 

## 2. Why is this issue important?
- To make solo storage provisioning is possible 
- Guidelines for new SP in the ecosystem 
- As training material for Storage Provider
- To understand the complexities of complexities of balancing the sector sealing process.

## 3. Tasks
1. Video tutorial on how to covers a 1PiB of RAW Power for Storage Provider setup by using a more efficient hardware on the latest Lotus version for storage provisioning 
2. Hardware Configuration 
3. How to deploy the cluster 

## 4. Additional Context

Reference:  https://www.google.com/search?q=filecoin+mining&tbm=vid

**Comment by benjaminh83** [comment]
Hi @vnessasgrt 
I would be happy to do a follow up on the SR workshop. I would think a similar setup, so some slides and real pictures of what a setup like this could look like. 
Setup would include a storage systems, but including the compute resources for the different lotus processes, including the market module for real data ingestion.

**Comment by vnessasgrt** [comment]
Awesome! Assigning this issue to @benjaminh83

**Comment by vnessasgrt** [comment]
Closing this issue and video can be find here: https://www.youtube.com/watch?v=LKMjCgo-fkA&t=598s
